#!/usr/bin/env bash
# Transfer a file from local to a Nginx web server

# Check if the number of arguments is incorrect
if [ $# -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY "
    exit 1
fi

# Accepting the arguments from the terminal
FILE="$1"
HOST_IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Transfer the file to the web server
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$FILE"  "$USERNAME@$HOST_IP:~/"
