#!/usr/bin/env bash
# Configure the Nginx server and sets up 301 - moved permanently

# Setting Nginx
sudo apt update
sudo apt-get update

sudo apt-get install -y nginx

# Create custom index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# edit the default file from sites-available
echo "
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /redirect_me {
            return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;
        }
    }
" | sudo tee /etc/nginx/sites-available/default 

# recreating the default file using symbolic link
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restarting the Nginx
sudo service nginx restart
