#!/usr/bin/env bash
# Setting Nginx sites-enalbed to listen to port 80

echo "
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
            try_files \$uri \$uri/ =404;
        }
    }
" | sudo tee /etc/nginx/sites-enabled/default

# Restart the server
sudo service nginx restart
