#!/usr/bin/env bash
# create a user called nginx and run nginx as nginx user
pkill apache2
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 666 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
